### ISSUE TITLE
Version number not bumped for 0.1.5 release

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/ChemDyg#38]
It looks like the version number is still 0.1.4:
https://github.com/E3SM-Project/ChemDyg/blob/v0.1.5/setup.cfg#L3

Please make sure to update the version number before tagging a release.

**Comment by hsiangheleellnl** [comment]
Thank you for catching the error. I released a new version with the version tag v0.1.5c.

**Comment by hsiangheleellnl** [comment]
@xylar Maybe I did it wrong again. Does the version tag have to be the same version in setup.cfg? If so, what should I do for the correction?

**Comment by xylar** [comment]
@hsiangheleellnl, it's best not to add letters like `v0.1.5c` because those have other meanings (see https://semver.org/).

It's not that big a deal that 0.1.5 had the wrong version number in `setup.cfg`.  I don't think it's worth trying to fix -- the only fix would be to release v0.1.6 with the correct version in `setup.cfg`.  Just please remember to bump the version number before tagging future versions.
